### ISSUE TITLE
Compile error (missing tp.idc)

### ISSUE THREAD

**Issue by bidaian** [Neo2SHYAlien/android#2]
make: *** No rule to make target `device/allwinner/flatfish/configs/tp.idc', needed by `out/target/product/flatfish/system/usr/idc/ft5x_ts.idc'.  Stop.

Any idea where that comes from or how to solve it?

**Comment by Neo2SHYAlien** [comment]
Look like you didn’t run extract script
```bash
cd device/allwinner/flatfish && ./extract-files.sh
```
This will put all vendor files on right places

**Comment by bidaian** [comment]
Ah, ok. My fault. I thought the "Add blobs from FirefoxOS into build tree" commit had already added all those files. Thanks for the prompt answer.
